name: Fx.Scroll.Carousel
author: rpflo
category: Effects
tags: [carousel, Fx.Scroll]
docs: http://moodocs.net/rpflo/mootools-rpflo/Fx.Scroll.Carousel
demo: http://mootools.net/shell/rpflo/LEb7H/embedded/result,js,html,css
current: 0.9